为了重新创建开发机

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/workspace/xll/Anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/workspace/xll/Anaconda3/etc/profile.d/conda.sh" ]; then
        . "/workspace/xll/Anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/workspace/xll/Anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
# conda activate auto
cd /workspace/xll